# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install necessary Python packages
RUN pip install --no-cache-dir flask flask-cors pandas scikit-learn 

# Expose the port the API runs on
EXPOSE 5000

# Define the command to run the service
CMD ["python", "fraud_api_pipeline.py"]
