version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: warranty-claim-api
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: warranty-claim-ui
    ports:
      - "8080:80"
    depends_on:
      - backend
